# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'


default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  port: 5432
  host: localhost
  username: postgres
  password: 12345678

development:
  <<: *default
  database: herokuapp_development

production:
  <<: *default
  database: herokuapp_production
  username: postgres
  password: 12345678
